Decsriptive readme
rhd-gitops-example/gitops pull request #3
Opened 2020-09-01 13:45 UTC by gaganhegde

The readme elaborates on the GitOps repo and the current directory structure.

2020-09-01 14:16 UTC, sbose78 commented
Would "sample repo" be a better name compared to "mock repo" ?

2020-09-01 14:28 UTC, bigkevmcd commented
Should also mention that this **cannot** be applied to a cluster, it will not work as the secrets are encrypted.

2020-09-01 15:23 UTC, bigkevmcd requested changes
Some minor changes needed I think.

2020-09-01 15:23 UTC, bigkevmcd commented on README.md
> +The given mock repo is an indication of the capability of the GitOps tool, the given repo structure constituting the entire GitOps configuration can be created by running a couple of day-1 and day-2
```suggestion
This is a sample output, generated by the bootstrapping tool, running a couple of day-1 and day-2 commands. A high level structure of thhis repository constitutes the config, environments folder and the pipelines.yaml file. 
```

2020-09-01 15:23 UTC, bigkevmcd commented on README.md
>  # Mock GitOps Repo
# Sample GitOps Repository

2020-09-02 09:45 UTC, bigkevmcd requested changes
I worry that we're duplicating a lot of the material from the docs repository (which is a maintenance cost).

2020-09-02 09:45 UTC, bigkevmcd commented on README.md
> +The pipelines.yaml is a representatioon of the current directory structure, it throws light on the essential bits of the GitOps repo. The current GitOps repo structure can be broken down based on the
```suggestion
The pipelines.yaml is a representation of the current directory structure, it throws light on the essential bits of the GitOps repo. The current GitOps repo structure can be broken down based on the pipelines.yaml file.
```

2020-09-02 09:45 UTC, bigkevmcd commented on README.md
> +The config directory refers to the special environments which contain the configuraion manifests for the argocd and cicd environments.
```suggestion
The config directory refers to the special environments which contain the configuration manifests for the ArgoCD and CI/CD environments.
```

2020-09-02 09:45 UTC, bigkevmcd commented on README.md
> +* #### Argocd sub-folder
Can we maybe agree on "ArgoCD" as the capitalisation for this ?

2020-09-02 09:45 UTC, bigkevmcd commented on README.md
> +  ArgoCD is used to perform Continuous Deployment of Applications. When an Application is created in the target Environment an ArgoCD application is also created and kept in the ArgoCD Environment. T
This sentence has a lot of initial capitals which is somewhat jarring, we could simplify it a bit.

2020-09-02 09:45 UTC, bigkevmcd commented on README.md
> +Within a Pipelines Model, there are many Environments which hold Applications and Services. Each Environment has its own namespace/project as defined in openshift. The sample environments directory h
T
```suggestion
Within the pipelines model, there are many environments which hold applications and services. Each environment has its own namespace/project as defined in OpenShift. The sample environments directory has the structure listed below.
```

2020-09-02 09:45 UTC, bigkevmcd commented on README.md
> +* #### (Plain Old) Environment:
What's _Plain Old_ in this context?

2020-09-02 09:45 UTC, bigkevmcd commented on README.md
> +This repository cannot be applied to the cluster since the sealed secrets are encrypted with accordance to the cluster at the time of creation of the repository.
This should be moved to the top.

Also "since the secrets are encrypted with the private key in the cluster at the time this repository was created." probably sounds better.

2020-09-14 16:15 UTC, bigkevmcd approved these changes
Looks good to me!

2020-09-14 16:32 UTC, merged